version: '3.3'
services:
  bookstack_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Calcutta
      - APP_URL=http://localhost:6875/
      - APP_KEY=base64:heXs+Xr7nkR4lRFxyXdR1cMfdPbBD6f3kmcBlpGqSWs=
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_DATABASE=db
      # - QUEUE_CONNECTION= #optional
    volumes:
      - /home/user/working/bookstack/config:/config
    ports:
      - 6875:80
    depends_on:
      - bookstack_db
    restart: unless-stopped
# Names our volume
volumes:
  my-db: 
    
